### ISSUE TITLE
angular aot build error

### ISSUE THREAD

**Issue by qingxo** [mezoistvan/ng2-flatpickr#20] opened 2017-08-31 11:39 UTC
when i run "node_modules/.bin/ngc -p tsconfig-aot.json"  ,it not work right ,it show info below

Unexpected value 'Ng2FlatpickrComponent in /Users/karas/projects/smart-raise/node_modules/ng2-flatpickr/src/ng2-flatpickr.component.d.ts' declared by the module 'HomeModule in /Users/karas/projects/smart-raise/src/app/home/home.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

How to solve the problem?

**Comment by mezoistvan** [comment] 2017-09-24 23:12
Duplicate of #19, closing

**Closed by mezoistvan** 2017-09-24 23:12 UTC
